In [1]:
# load dataset
import pandas as pd
df = pd.read_excel("Crop_recommendation.xlsx")
df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [2]:
# Preprocess (encode + scale + split)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
import tensorflow as tf

X = df.drop(columns=["label"])
y = df["label"]

le = LabelEncoder()
y_enc = le.fit_transform(y)

y_ohe = tf.keras.utils.to_categorical(y_enc)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_ohe, test_size=0.2, random_state=42, stratify=y_enc
)

In [3]:
#Evaluation Helper
from sklearn.metrics import accuracy_score, classification_report
import numpy as np

def evaluate(model, X_test, y_test):
    y_true = np.argmax(y_test, axis=1)
    y_pred_prob = model.predict(X_test)
    y_pred = np.argmax(y_pred_prob, axis=1)
    acc = accuracy_score(y_true, y_pred)
    print("Accuracy:", acc)
    print(classification_report(y_true, y_pred, target_names=le.classes_))
    return acc

In [4]:
#ALGO 1 — DNN / MLP
#Build MLP
from tensorflow.keras import layers, models

input_dim = X_train.shape[1]
num_classes = y_train.shape[1]

mlp = models.Sequential([
    layers.Dense(128, activation='relu', input_shape=(input_dim,)),
    layers.Dropout(0.3),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(num_classes, activation='softmax')
])

mlp.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
mlp.summary()

c:\Users\ashee\Desktop\crop project\venv\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         1,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 22)             │         1,430 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,710 (41.84 KB)

 Trainable params: 10,710 (41.84 KB)

 Non-trainable params: 0 (0.00 B)

In [5]:
#Train MLP
from tensorflow.keras.callbacks import EarlyStopping

es = EarlyStopping(monitor='val_loss', patience=8, restore_best_weights=True)

mlp.fit(
    X_train, y_train,
    validation_split=0.1,
    epochs=80,
    batch_size=32,
    callbacks=[es],
    verbose=2
)

acc_mlp = evaluate(mlp, X_test, y_test)

Epoch 1/80
50/50 - 1s - 15ms/step - accuracy: 0.1730 - loss: 2.7938 - val_accuracy: 0.5057 - val_loss: 2.2301
Epoch 2/80
50/50 - 0s - 2ms/step - accuracy: 0.4634 - loss: 1.9921 - val_accuracy: 0.6705 - val_loss: 1.3418
Epoch 3/80
50/50 - 0s - 2ms/step - accuracy: 0.6155 - loss: 1.3143 - val_accuracy: 0.8807 - val_loss: 0.7685
Epoch 4/80
50/50 - 0s - 2ms/step - accuracy: 0.7052 - loss: 0.9221 - val_accuracy: 0.8068 - val_loss: 0.5401
Epoch 5/80
50/50 - 0s - 2ms/step - accuracy: 0.7588 - loss: 0.7178 - val_accuracy: 0.8920 - val_loss: 0.4082
Epoch 6/80
50/50 - 0s - 2ms/step - accuracy: 0.7860 - loss: 0.6088 - val_accuracy: 0.9318 - val_loss: 0.3283
Epoch 7/80
50/50 - 0s - 2ms/step - accuracy: 0.8226 - loss: 0.5342 - val_accuracy: 0.9318 - val_loss: 0.2860
Epoch 8/80
50/50 - 0s - 2ms/step - accuracy: 0.8245 - loss: 0.4826 - val_accuracy: 0.9489 - val_loss: 0.2442
Epoch 9/80
50/50 - 0s - 2ms/step - accuracy: 0.8523 - loss: 0.4319 - val_accuracy: 0.9261 - val_loss: 0.2302
Epoch 10/80
50/50 - 0s - 3ms/step - accuracy: 0.8573 - loss: 0.4022 - val_accuracy: 0.9148 - val_loss: 0.2141
Epoch 11/80
50/50 - 0s - 2ms/step - accuracy: 0.8662 - loss: 0.3687 - val_accuracy: 0.9489 - val_loss: 0.1794
Epoch 12/80
50/50 - 0s - 2ms/step - accuracy: 0.8775 - loss: 0.3517 - val_accuracy: 0.9375 - val_loss: 0.1774
Epoch 13/80
50/50 - 0s - 2ms/step - accuracy: 0.8971 - loss: 0.3186 - val_accuracy: 0.9545 - val_loss: 0.1622
Epoch 14/80
50/50 - 0s - 2ms/step - accuracy: 0.8914 - loss: 0.3110 - val_accuracy: 0.9432 - val_loss: 0.1512
Epoch 15/80
50/50 - 0s - 2ms/step - accuracy: 0.9047 - loss: 0.2760 - val_accuracy: 0.9716 - val_loss: 0.1359
Epoch 16/80
50/50 - 0s - 2ms/step - accuracy: 0.9122 - loss: 0.2565 - val_accuracy: 0.9489 - val_loss: 0.1392
Epoch 17/80
50/50 - 0s - 2ms/step - accuracy: 0.9192 - loss: 0.2411 - val_accuracy: 0.9659 - val_loss: 0.1199
Epoch 18/80
50/50 - 0s - 2ms/step - accuracy: 0.9179 - loss: 0.2415 - val_accuracy: 0.9545 - val_loss: 0.1200
Epoch 19/80
50/50 - 0s - 2ms/step - accuracy: 0.9198 - loss: 0.2313 - val_accuracy: 0.9602 - val_loss: 0.1118
Epoch 20/80
50/50 - 0s - 2ms/step - accuracy: 0.9242 - loss: 0.2214 - val_accuracy: 0.9659 - val_loss: 0.1108
Epoch 21/80
50/50 - 0s - 2ms/step - accuracy: 0.9287 - loss: 0.2118 - val_accuracy: 0.9716 - val_loss: 0.1041
Epoch 22/80
50/50 - 0s - 2ms/step - accuracy: 0.9318 - loss: 0.1933 - val_accuracy: 0.9602 - val_loss: 0.1084
Epoch 23/80
50/50 - 0s - 2ms/step - accuracy: 0.9274 - loss: 0.2139 - val_accuracy: 0.9602 - val_loss: 0.0990
Epoch 24/80
50/50 - 0s - 2ms/step - accuracy: 0.9331 - loss: 0.1997 - val_accuracy: 0.9602 - val_loss: 0.0984
Epoch 25/80
50/50 - 0s - 2ms/step - accuracy: 0.9280 - loss: 0.1938 - val_accuracy: 0.9602 - val_loss: 0.0993
Epoch 26/80
50/50 - 0s - 2ms/step - accuracy: 0.9451 - loss: 0.1717 - val_accuracy: 0.9602 - val_loss: 0.0896
Epoch 27/80
50/50 - 0s - 2ms/step - accuracy: 0.9375 - loss: 0.1731 - val_accuracy: 0.9545 - val_loss: 0.0960
Epoch 28/80
50/50 - 0s - 2ms/step - accuracy: 0.9324 - loss: 0.1815 - val_accuracy: 0.9716 - val_loss: 0.0940
Epoch 29/80
50/50 - 0s - 2ms/step - accuracy: 0.9508 - loss: 0.1459 - val_accuracy: 0.9659 - val_loss: 0.0895
Epoch 30/80
50/50 - 0s - 2ms/step - accuracy: 0.9432 - loss: 0.1616 - val_accuracy: 0.9659 - val_loss: 0.0848
Epoch 31/80
50/50 - 0s - 2ms/step - accuracy: 0.9337 - loss: 0.1650 - val_accuracy: 0.9489 - val_loss: 0.1026
Epoch 32/80
50/50 - 0s - 2ms/step - accuracy: 0.9495 - loss: 0.1490 - val_accuracy: 0.9602 - val_loss: 0.0850
Epoch 33/80
50/50 - 0s - 2ms/step - accuracy: 0.9426 - loss: 0.1509 - val_accuracy: 0.9602 - val_loss: 0.0939
Epoch 34/80
50/50 - 0s - 2ms/step - accuracy: 0.9476 - loss: 0.1486 - val_accuracy: 0.9716 - val_loss: 0.0838
Epoch 35/80
50/50 - 0s - 2ms/step - accuracy: 0.9533 - loss: 0.1372 - val_accuracy: 0.9659 - val_loss: 0.0805
Epoch 36/80
50/50 - 0s - 2ms/step - accuracy: 0.9457 - loss: 0.1473 - val_accuracy: 0.9716 - val_loss: 0.0868
Epoch 37/80
50/50 - 0s - 2ms/step - accuracy: 0.9362 - loss: 0.1522 - val_accuracy: 0.9602 - val_loss: 0.0793
Epoch 38/80
50/50 - 0s - 2ms/step - accuracy: 0.9564 - loss: 0.1275 - val_accuracy: 0.9602 - val_loss: 0.0817
Epoch 39/80
50/50 - 0s - 2ms/step - accuracy: 0.9470 - loss: 0.1398 - val_accuracy: 0.9659 - val_loss: 0.0795
Epoch 40/80
50/50 - 0s - 2ms/step - accuracy: 0.9558 - loss: 0.1258 - val_accuracy: 0.9659 - val_loss: 0.0739
Epoch 41/80
50/50 - 0s - 3ms/step - accuracy: 0.9539 - loss: 0.1321 - val_accuracy: 0.9659 - val_loss: 0.0702
Epoch 42/80
50/50 - 0s - 2ms/step - accuracy: 0.9508 - loss: 0.1373 - val_accuracy: 0.9545 - val_loss: 0.0742
Epoch 43/80
50/50 - 0s - 2ms/step - accuracy: 0.9545 - loss: 0.1253 - val_accuracy: 0.9602 - val_loss: 0.0812
Epoch 44/80
50/50 - 0s - 2ms/step - accuracy: 0.9539 - loss: 0.1280 - val_accuracy: 0.9716 - val_loss: 0.0813
Epoch 45/80
50/50 - 0s - 2ms/step - accuracy: 0.9602 - loss: 0.1148 - val_accuracy: 0.9659 - val_loss: 0.0781
Epoch 46/80
50/50 - 0s - 2ms/step - accuracy: 0.9552 - loss: 0.1125 - val_accuracy: 0.9602 - val_loss: 0.0719
Epoch 47/80
50/50 - 0s - 2ms/step - accuracy: 0.9602 - loss: 0.1193 - val_accuracy: 0.9659 - val_loss: 0.0737
Epoch 48/80
50/50 - 0s - 2ms/step - accuracy: 0.9545 - loss: 0.1211 - val_accuracy: 0.9830 - val_loss: 0.0689
Epoch 49/80
50/50 - 0s - 2ms/step - accuracy: 0.9634 - loss: 0.1108 - val_accuracy: 0.9716 - val_loss: 0.0645
Epoch 50/80
50/50 - 0s - 2ms/step - accuracy: 0.9520 - loss: 0.1246 - val_accuracy: 0.9716 - val_loss: 0.0736
Epoch 51/80
50/50 - 0s - 2ms/step - accuracy: 0.9545 - loss: 0.1244 - val_accuracy: 0.9716 - val_loss: 0.0744
Epoch 52/80
50/50 - 0s - 2ms/step - accuracy: 0.9602 - loss: 0.1096 - val_accuracy: 0.9773 - val_loss: 0.0659
Epoch 53/80
50/50 - 0s - 2ms/step - accuracy: 0.9571 - loss: 0.1147 - val_accuracy: 0.9773 - val_loss: 0.0667
Epoch 54/80
50/50 - 0s - 2ms/step - accuracy: 0.9590 - loss: 0.1095 - val_accuracy: 0.9716 - val_loss: 0.0705
Epoch 55/80
50/50 - 0s - 2ms/step - accuracy: 0.9558 - loss: 0.1151 - val_accuracy: 0.9659 - val_loss: 0.0701
Epoch 56/80
50/50 - 0s - 2ms/step - accuracy: 0.9621 - loss: 0.1053 - val_accuracy: 0.9659 - val_loss: 0.0659
Epoch 57/80
50/50 - 0s - 2ms/step - accuracy: 0.9602 - loss: 0.1079 - val_accuracy: 0.9659 - val_loss: 0.0676
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Accuracy: 0.9840909090909091
              precision    recall  f1-score   support

       apple       1.00      1.00      1.00        20
      banana       1.00      1.00      1.00        20
   blackgram       0.95      1.00      0.98        20
    chickpea       1.00      1.00      1.00        20
     coconut       1.00      1.00      1.00        20
      coffee       1.00      1.00      1.00        20
      cotton       0.95      1.00      0.98        20
      grapes       1.00      1.00      1.00        20
        jute       0.90      0.95      0.93        20
 kidneybeans       0.95      1.00      0.98        20
      lentil       1.00      0.95      0.97        20
       maize       1.00      0.95      0.97        20
       mango       1.00      1.00      1.00        20
   mothbeans       1.00      1.00      1.00        20
    mungbean       1.00      1.00      1.00        20
   muskmelon       0.95      1.00      0.98        20
      orange       1.00      1.00      1.00        20
      papaya       1.00      1.00      1.00        20
  pigeonpeas       1.00      0.95      0.97        20
 pomegranate       1.00      1.00      1.00        20
        rice       0.95      0.90      0.92        20
  watermelon       1.00      0.95      0.97        20

    accuracy                           0.98       440
   macro avg       0.98      0.98      0.98       440
weighted avg       0.98      0.98      0.98       440

In [6]:
#tabnet algo
#Prepare Data For TabNet
from pytorch_tabnet.tab_model import TabNetClassifier
import numpy as np

X_raw = df.drop(columns=["label"]).values
y_raw = y_enc

from sklearn.model_selection import train_test_split
X_train_t, X_test_t, y_train_t, y_test_t = train_test_split(
    X_raw, y_raw, test_size=0.2, random_state=42, stratify=y_raw
)

In [15]:
#Train TabNet
tabnet = TabNetClassifier()

tabnet.fit(
    X_train_t, y_train_t,
    eval_set=[(X_test_t, y_test_t)],
    patience=10,
    max_epochs=100
)
acc_tabnet = accuracy_score(y_test_t, y_pred_t)

c:\Users\ashee\Desktop\crop project\venv\Lib\site-packages\pytorch_tabnet\abstract_model.py:82: UserWarning: Device used : cpu
  warnings.warn(f"Device used : {self.device}")

epoch 0  | loss: 3.9135  | val_0_accuracy: 0.04091 |  0:00:00s
epoch 1  | loss: 3.40034 | val_0_accuracy: 0.08409 |  0:00:00s
epoch 2  | loss: 3.12377 | val_0_accuracy: 0.05682 |  0:00:00s
epoch 3  | loss: 2.96955 | val_0_accuracy: 0.05682 |  0:00:00s
epoch 4  | loss: 2.82263 | val_0_accuracy: 0.075   |  0:00:00s
epoch 5  | loss: 2.70233 | val_0_accuracy: 0.10227 |  0:00:00s
epoch 6  | loss: 2.64295 | val_0_accuracy: 0.09545 |  0:00:00s
epoch 7  | loss: 2.555   | val_0_accuracy: 0.07045 |  0:00:00s
epoch 8  | loss: 2.5162  | val_0_accuracy: 0.06136 |  0:00:00s
epoch 9  | loss: 2.43557 | val_0_accuracy: 0.07273 |  0:00:00s
epoch 10 | loss: 2.35808 | val_0_accuracy: 0.06364 |  0:00:00s
epoch 11 | loss: 2.28824 | val_0_accuracy: 0.06591 |  0:00:00s
epoch 12 | loss: 2.23772 | val_0_accuracy: 0.06591 |  0:00:00s
epoch 13 | loss: 2.17381 | val_0_accuracy: 0.07273 |  0:00:00s
epoch 14 | loss: 2.11166 | val_0_accuracy: 0.07045 |  0:00:00s
epoch 15 | loss: 2.07146 | val_0_accuracy: 0.05909 |  0:00:00s

Early stopping occurred at epoch 15 with best_epoch = 5 and best_val_0_accuracy = 0.10227

c:\Users\ashee\Desktop\crop project\venv\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

In [8]:
#Evaluate TabNet
y_pred_t = tabnet.predict(X_test_t)
from sklearn.metrics import accuracy_score, classification_report

acc_tabnet = accuracy_score(y_test_t, y_pred_t)
print("TabNet Accuracy:", acc_tabnet)
print(classification_report(y_test_t, y_pred_t, target_names=le.classes_))

TabNet Accuracy: 0.10227272727272728
              precision    recall  f1-score   support

       apple       0.09      0.60      0.16        20
      banana       0.00      0.00      0.00        20
   blackgram       0.00      0.00      0.00        20
    chickpea       0.00      0.00      0.00        20
     coconut       0.00      0.00      0.00        20
      coffee       0.00      0.00      0.00        20
      cotton       0.00      0.00      0.00        20
      grapes       0.00      0.00      0.00        20
        jute       0.00      0.00      0.00        20
 kidneybeans       0.25      0.05      0.08        20
      lentil       0.00      0.00      0.00        20
       maize       0.00      0.00      0.00        20
       mango       0.00      0.00      0.00        20
   mothbeans       0.00      0.00      0.00        20
    mungbean       0.26      0.80      0.40        20
   muskmelon       0.00      0.00      0.00        20
      orange       0.08      0.80      0.14        20
      papaya       0.00      0.00      0.00        20
  pigeonpeas       0.00      0.00      0.00        20
 pomegranate       0.00      0.00      0.00        20
        rice       0.00      0.00      0.00        20
  watermelon       0.00      0.00      0.00        20

    accuracy                           0.10       440
   macro avg       0.03      0.10      0.04       440
weighted avg       0.03      0.10      0.04       440

c:\Users\ashee\Desktop\crop project\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ashee\Desktop\crop project\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ashee\Desktop\crop project\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [11]:
# reshape data for Transformer

import numpy as np

input_dim = X_train.shape[1]        
num_classes = y_train.shape[1]     

X_train_tr = X_train.reshape(-1, input_dim, 1)
X_test_tr  = X_test.reshape(-1, input_dim, 1)

print("Transformer input shape:", X_train_tr.shape)

Transformer input shape: (1760, 7, 1)

In [12]:
#Build Transformer model


from tensorflow.keras import layers, models

d_model = 32    
num_heads = 4   

inp = layers.Input(shape=(input_dim, 1)) 


x = layers.Dense(d_model)(inp) 


attn_out = layers.MultiHeadAttention(num_heads=num_heads, key_dim=d_model)(
    x, x
)
x = layers.Add()([x, attn_out])         
x = layers.LayerNormalization()(x)


ffn = layers.Dense(64, activation='relu')(x)
ffn = layers.Dense(d_model, activation='relu')(ffn)
x = layers.Add()([x, ffn])             
x = layers.LayerNormalization()(x)


x = layers.GlobalAveragePooling1D()(x)


x = layers.Dense(64, activation='relu')(x)
out = layers.Dense(num_classes, activation='softmax')(x)

transformer_model = models.Model(inputs=inp, outputs=out)

transformer_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

transformer_model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_1       │ (None, 7, 1)      │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 7, 32)     │         64 │ input_layer_1[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multi_head_attenti… │ (None, 7, 32)     │     16,800 │ dense_3[0][0],    │
│ (MultiHeadAttentio… │                   │            │ dense_3[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add (Add)           │ (None, 7, 32)     │          0 │ dense_3[0][0],    │
│                     │                   │            │ multi_head_atten… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalization │ (None, 7, 32)     │         64 │ add[0][0]         │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_4 (Dense)     │ (None, 7, 64)     │      2,112 │ layer_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_5 (Dense)     │ (None, 7, 32)     │      2,080 │ dense_4[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_1 (Add)         │ (None, 7, 32)     │          0 │ layer_normalizat… │
│                     │                   │            │ dense_5[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalizatio… │ (None, 7, 32)     │         64 │ add_1[0][0]       │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ global_average_poo… │ (None, 32)        │          0 │ layer_normalizat… │
│ (GlobalAveragePool… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_6 (Dense)     │ (None, 64)        │      2,112 │ global_average_p… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_7 (Dense)     │ (None, 22)        │      1,430 │ dense_6[0][0]     │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 24,726 (96.59 KB)

 Trainable params: 24,726 (96.59 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
#Train Transformer model

from tensorflow.keras.callbacks import EarlyStopping

es_tr = EarlyStopping(monitor='val_loss', patience=8, restore_best_weights=True)

history_tr = transformer_model.fit(
    X_train_tr, y_train,
    validation_split=0.1,
    epochs=80,
    batch_size=32,
    callbacks=[es_tr],
    verbose=2
)

print("Transformer-like model evaluation:")
acc_trans = evaluate(transformer_model, X_test_tr, y_test)

Epoch 1/80
50/50 - 3s - 50ms/step - accuracy: 0.1364 - loss: 2.8205 - val_accuracy: 0.1420 - val_loss: 2.5832
Epoch 2/80
50/50 - 0s - 6ms/step - accuracy: 0.2027 - loss: 2.3950 - val_accuracy: 0.2670 - val_loss: 2.2543
Epoch 3/80
50/50 - 0s - 5ms/step - accuracy: 0.3163 - loss: 2.1213 - val_accuracy: 0.2841 - val_loss: 2.0162
Epoch 4/80
50/50 - 0s - 5ms/step - accuracy: 0.3504 - loss: 1.8994 - val_accuracy: 0.3864 - val_loss: 1.8084
Epoch 5/80
50/50 - 0s - 6ms/step - accuracy: 0.4255 - loss: 1.6914 - val_accuracy: 0.4432 - val_loss: 1.6222
Epoch 6/80
50/50 - 0s - 5ms/step - accuracy: 0.4514 - loss: 1.5617 - val_accuracy: 0.4545 - val_loss: 1.5151
Epoch 7/80
50/50 - 0s - 5ms/step - accuracy: 0.4773 - loss: 1.4498 - val_accuracy: 0.5000 - val_loss: 1.4253
Epoch 8/80
50/50 - 0s - 5ms/step - accuracy: 0.5120 - loss: 1.3863 - val_accuracy: 0.4773 - val_loss: 1.3656
Epoch 9/80
50/50 - 0s - 5ms/step - accuracy: 0.5057 - loss: 1.3450 - val_accuracy: 0.5227 - val_loss: 1.3172
Epoch 10/80
50/50 - 0s - 5ms/step - accuracy: 0.5133 - loss: 1.3075 - val_accuracy: 0.5455 - val_loss: 1.2825
Epoch 11/80
50/50 - 0s - 5ms/step - accuracy: 0.5341 - loss: 1.2738 - val_accuracy: 0.5114 - val_loss: 1.2499
Epoch 12/80
50/50 - 0s - 6ms/step - accuracy: 0.5341 - loss: 1.2328 - val_accuracy: 0.5398 - val_loss: 1.2603
Epoch 13/80
50/50 - 0s - 5ms/step - accuracy: 0.5391 - loss: 1.2375 - val_accuracy: 0.5795 - val_loss: 1.1966
Epoch 14/80
50/50 - 0s - 5ms/step - accuracy: 0.5473 - loss: 1.1950 - val_accuracy: 0.5568 - val_loss: 1.1879
Epoch 15/80
50/50 - 0s - 5ms/step - accuracy: 0.5530 - loss: 1.2123 - val_accuracy: 0.5909 - val_loss: 1.1999
Epoch 16/80
50/50 - 0s - 5ms/step - accuracy: 0.5694 - loss: 1.1679 - val_accuracy: 0.6080 - val_loss: 1.1539
Epoch 17/80
50/50 - 0s - 5ms/step - accuracy: 0.5808 - loss: 1.1385 - val_accuracy: 0.6023 - val_loss: 1.1291
Epoch 18/80
50/50 - 0s - 5ms/step - accuracy: 0.5777 - loss: 1.1208 - val_accuracy: 0.5852 - val_loss: 1.1275
Epoch 19/80
50/50 - 0s - 5ms/step - accuracy: 0.5859 - loss: 1.1260 - val_accuracy: 0.6193 - val_loss: 1.0787
Epoch 20/80
50/50 - 0s - 5ms/step - accuracy: 0.5707 - loss: 1.1248 - val_accuracy: 0.6136 - val_loss: 1.0996
Epoch 21/80
50/50 - 0s - 6ms/step - accuracy: 0.5960 - loss: 1.0984 - val_accuracy: 0.5341 - val_loss: 1.2429
Epoch 22/80
50/50 - 0s - 5ms/step - accuracy: 0.5979 - loss: 1.0947 - val_accuracy: 0.6364 - val_loss: 1.0915
Epoch 23/80
50/50 - 0s - 5ms/step - accuracy: 0.6111 - loss: 1.0565 - val_accuracy: 0.6591 - val_loss: 1.0354
Epoch 24/80
50/50 - 0s - 6ms/step - accuracy: 0.5979 - loss: 1.0495 - val_accuracy: 0.6193 - val_loss: 1.0722
Epoch 25/80
50/50 - 0s - 6ms/step - accuracy: 0.6136 - loss: 1.0574 - val_accuracy: 0.6761 - val_loss: 1.0176
Epoch 26/80
50/50 - 0s - 5ms/step - accuracy: 0.6168 - loss: 1.0387 - val_accuracy: 0.6136 - val_loss: 1.0180
Epoch 27/80
50/50 - 0s - 5ms/step - accuracy: 0.6212 - loss: 1.0277 - val_accuracy: 0.6932 - val_loss: 0.9967
Epoch 28/80
50/50 - 0s - 5ms/step - accuracy: 0.6174 - loss: 1.0331 - val_accuracy: 0.6875 - val_loss: 0.9620
Epoch 29/80
50/50 - 0s - 6ms/step - accuracy: 0.6294 - loss: 1.0204 - val_accuracy: 0.6250 - val_loss: 1.0479
Epoch 30/80
50/50 - 0s - 5ms/step - accuracy: 0.6332 - loss: 1.0044 - val_accuracy: 0.6250 - val_loss: 1.0698
Epoch 31/80
50/50 - 0s - 5ms/step - accuracy: 0.6389 - loss: 0.9886 - val_accuracy: 0.6534 - val_loss: 0.9729
Epoch 32/80
50/50 - 0s - 5ms/step - accuracy: 0.6332 - loss: 0.9909 - val_accuracy: 0.6761 - val_loss: 1.0082
Epoch 33/80
50/50 - 0s - 5ms/step - accuracy: 0.6370 - loss: 1.0018 - val_accuracy: 0.6932 - val_loss: 0.9553
Epoch 34/80
50/50 - 0s - 5ms/step - accuracy: 0.6446 - loss: 0.9663 - val_accuracy: 0.6818 - val_loss: 0.9428
Epoch 35/80
50/50 - 0s - 5ms/step - accuracy: 0.6591 - loss: 0.9547 - val_accuracy: 0.6932 - val_loss: 0.9641
Epoch 36/80
50/50 - 0s - 5ms/step - accuracy: 0.6515 - loss: 0.9485 - val_accuracy: 0.6705 - val_loss: 0.9578
Epoch 37/80
50/50 - 0s - 5ms/step - accuracy: 0.6534 - loss: 0.9654 - val_accuracy: 0.7102 - val_loss: 0.9017
Epoch 38/80
50/50 - 0s - 5ms/step - accuracy: 0.6496 - loss: 0.9307 - val_accuracy: 0.6989 - val_loss: 0.8973
Epoch 39/80
50/50 - 0s - 5ms/step - accuracy: 0.6780 - loss: 0.9026 - val_accuracy: 0.7330 - val_loss: 0.9074
Epoch 40/80
50/50 - 0s - 5ms/step - accuracy: 0.6755 - loss: 0.9030 - val_accuracy: 0.6989 - val_loss: 0.9148
Epoch 41/80
50/50 - 0s - 5ms/step - accuracy: 0.6705 - loss: 0.9140 - val_accuracy: 0.6932 - val_loss: 0.9071
Epoch 42/80
50/50 - 0s - 5ms/step - accuracy: 0.6806 - loss: 0.8842 - val_accuracy: 0.6932 - val_loss: 0.8989
Epoch 43/80
50/50 - 0s - 5ms/step - accuracy: 0.6824 - loss: 0.8897 - val_accuracy: 0.7216 - val_loss: 0.8747
Epoch 44/80
50/50 - 0s - 5ms/step - accuracy: 0.6755 - loss: 0.8892 - val_accuracy: 0.7216 - val_loss: 0.8829
Epoch 45/80
50/50 - 0s - 5ms/step - accuracy: 0.6875 - loss: 0.8646 - val_accuracy: 0.7386 - val_loss: 0.8487
Epoch 46/80
50/50 - 0s - 5ms/step - accuracy: 0.6799 - loss: 0.8756 - val_accuracy: 0.7273 - val_loss: 0.8958
Epoch 47/80
50/50 - 0s - 5ms/step - accuracy: 0.6818 - loss: 0.8634 - val_accuracy: 0.6761 - val_loss: 0.8882
Epoch 48/80
50/50 - 0s - 5ms/step - accuracy: 0.6919 - loss: 0.8531 - val_accuracy: 0.7614 - val_loss: 0.8176
Epoch 49/80
50/50 - 0s - 5ms/step - accuracy: 0.6944 - loss: 0.8443 - val_accuracy: 0.7557 - val_loss: 0.8249
Epoch 50/80
50/50 - 0s - 5ms/step - accuracy: 0.6970 - loss: 0.8521 - val_accuracy: 0.6932 - val_loss: 0.8489
Epoch 51/80
50/50 - 0s - 5ms/step - accuracy: 0.6843 - loss: 0.8223 - val_accuracy: 0.7500 - val_loss: 0.8141
Epoch 52/80
50/50 - 0s - 5ms/step - accuracy: 0.7033 - loss: 0.8287 - val_accuracy: 0.7443 - val_loss: 0.8687
Epoch 53/80
50/50 - 0s - 5ms/step - accuracy: 0.6982 - loss: 0.8291 - val_accuracy: 0.7330 - val_loss: 0.8124
Epoch 54/80
50/50 - 0s - 6ms/step - accuracy: 0.6982 - loss: 0.8192 - val_accuracy: 0.7500 - val_loss: 0.7880
Epoch 55/80
50/50 - 0s - 5ms/step - accuracy: 0.6982 - loss: 0.8179 - val_accuracy: 0.7102 - val_loss: 0.8579
Epoch 56/80
50/50 - 0s - 5ms/step - accuracy: 0.6995 - loss: 0.8202 - val_accuracy: 0.7159 - val_loss: 0.8358
Epoch 57/80
50/50 - 0s - 5ms/step - accuracy: 0.6982 - loss: 0.8151 - val_accuracy: 0.7670 - val_loss: 0.8010
Epoch 58/80
50/50 - 0s - 5ms/step - accuracy: 0.7153 - loss: 0.7898 - val_accuracy: 0.7216 - val_loss: 0.7846
Epoch 59/80
50/50 - 0s - 5ms/step - accuracy: 0.7140 - loss: 0.8063 - val_accuracy: 0.6932 - val_loss: 0.8659
Epoch 60/80
50/50 - 0s - 5ms/step - accuracy: 0.7102 - loss: 0.7791 - val_accuracy: 0.7443 - val_loss: 0.7720
Epoch 61/80
50/50 - 0s - 5ms/step - accuracy: 0.7191 - loss: 0.7612 - val_accuracy: 0.7443 - val_loss: 0.7960
Epoch 62/80
50/50 - 0s - 5ms/step - accuracy: 0.7203 - loss: 0.7569 - val_accuracy: 0.7500 - val_loss: 0.7919
Epoch 63/80
50/50 - 0s - 5ms/step - accuracy: 0.7115 - loss: 0.7672 - val_accuracy: 0.7784 - val_loss: 0.7482
Epoch 64/80
50/50 - 0s - 6ms/step - accuracy: 0.7241 - loss: 0.7656 - val_accuracy: 0.7102 - val_loss: 0.8226
Epoch 65/80
50/50 - 0s - 5ms/step - accuracy: 0.7128 - loss: 0.7599 - val_accuracy: 0.7614 - val_loss: 0.7534
Epoch 66/80
50/50 - 0s - 6ms/step - accuracy: 0.7254 - loss: 0.7506 - val_accuracy: 0.7330 - val_loss: 0.7632
Epoch 67/80
50/50 - 0s - 5ms/step - accuracy: 0.7229 - loss: 0.7654 - val_accuracy: 0.7898 - val_loss: 0.7694
Epoch 68/80
50/50 - 0s - 5ms/step - accuracy: 0.7355 - loss: 0.7307 - val_accuracy: 0.7443 - val_loss: 0.8091
Epoch 69/80
50/50 - 0s - 5ms/step - accuracy: 0.7298 - loss: 0.7320 - val_accuracy: 0.7443 - val_loss: 0.8603
Epoch 70/80
50/50 - 0s - 6ms/step - accuracy: 0.7140 - loss: 0.7572 - val_accuracy: 0.7386 - val_loss: 0.8309
Epoch 71/80
50/50 - 0s - 5ms/step - accuracy: 0.7298 - loss: 0.7156 - val_accuracy: 0.7841 - val_loss: 0.7543
Transformer-like model evaluation:
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
Accuracy: 0.6886363636363636
              precision    recall  f1-score   support

       apple       0.91      1.00      0.95        20
      banana       0.57      0.80      0.67        20
   blackgram       0.65      0.85      0.74        20
    chickpea       0.86      0.95      0.90        20
     coconut       0.59      0.80      0.68        20
      coffee       0.50      0.45      0.47        20
      cotton       0.78      0.70      0.74        20
      grapes       0.90      0.95      0.93        20
        jute       0.61      0.55      0.58        20
 kidneybeans       0.91      1.00      0.95        20
      lentil       0.45      0.25      0.32        20
       maize       0.55      0.55      0.55        20
       mango       0.65      0.75      0.70        20
   mothbeans       0.75      0.45      0.56        20
    mungbean       0.68      0.95      0.79        20
   muskmelon       0.82      0.90      0.86        20
      orange       0.55      0.55      0.55        20
      papaya       0.62      0.50      0.56        20
  pigeonpeas       0.86      0.30      0.44        20
 pomegranate       0.67      0.70      0.68        20
        rice       0.47      0.40      0.43        20
  watermelon       0.76      0.80      0.78        20

    accuracy                           0.69       440
   macro avg       0.69      0.69      0.67       440
weighted avg       0.69      0.69      0.67       440

In [17]:
# ALGO 4 — Autoencoder + DNN

from tensorflow.keras import layers, models

encoding_dim = 4

input_layer = layers.Input(shape=(input_dim,))
encoded = layers.Dense(32, activation='relu')(input_layer)
encoded = layers.Dense(encoding_dim, activation='relu')(encoded)

decoded = layers.Dense(32, activation='relu')(encoded)
decoded = layers.Dense(input_dim, activation='linear')(decoded)

autoencoder = models.Model(input_layer, decoded)
encoder = models.Model(input_layer, encoded)

autoencoder.compile(optimizer='adam', loss='mse')

autoencoder.fit(
    X_train, X_train,
    validation_split=0.1,
    epochs=80,
    batch_size=32,
    verbose=2
)

Epoch 1/80
50/50 - 1s - 17ms/step - loss: 0.9205 - val_loss: 0.9112
Epoch 2/80
50/50 - 0s - 3ms/step - loss: 0.7800 - val_loss: 0.7636
Epoch 3/80
50/50 - 0s - 3ms/step - loss: 0.6337 - val_loss: 0.5663
Epoch 4/80
50/50 - 0s - 3ms/step - loss: 0.4874 - val_loss: 0.4526
Epoch 5/80
50/50 - 0s - 3ms/step - loss: 0.4069 - val_loss: 0.3738
Epoch 6/80
50/50 - 0s - 3ms/step - loss: 0.3295 - val_loss: 0.2991
Epoch 7/80
50/50 - 0s - 4ms/step - loss: 0.2727 - val_loss: 0.2536
Epoch 8/80
50/50 - 0s - 3ms/step - loss: 0.2320 - val_loss: 0.2221
Epoch 9/80
50/50 - 0s - 3ms/step - loss: 0.2042 - val_loss: 0.1958
Epoch 10/80
50/50 - 0s - 3ms/step - loss: 0.1829 - val_loss: 0.1787
Epoch 11/80
50/50 - 0s - 3ms/step - loss: 0.1679 - val_loss: 0.1686
Epoch 12/80
50/50 - 0s - 3ms/step - loss: 0.1572 - val_loss: 0.1568
Epoch 13/80
50/50 - 0s - 3ms/step - loss: 0.1496 - val_loss: 0.1511
Epoch 14/80
50/50 - 0s - 3ms/step - loss: 0.1429 - val_loss: 0.1445
Epoch 15/80
50/50 - 0s - 3ms/step - loss: 0.1363 - val_loss: 0.1388
Epoch 16/80
50/50 - 0s - 3ms/step - loss: 0.1310 - val_loss: 0.1377
Epoch 17/80
50/50 - 0s - 3ms/step - loss: 0.1268 - val_loss: 0.1290
Epoch 18/80
50/50 - 0s - 3ms/step - loss: 0.1215 - val_loss: 0.1230
Epoch 19/80
50/50 - 0s - 3ms/step - loss: 0.1174 - val_loss: 0.1183
Epoch 20/80
50/50 - 0s - 3ms/step - loss: 0.1136 - val_loss: 0.1144
Epoch 21/80
50/50 - 0s - 3ms/step - loss: 0.1100 - val_loss: 0.1111
Epoch 22/80
50/50 - 0s - 3ms/step - loss: 0.1066 - val_loss: 0.1093
Epoch 23/80
50/50 - 0s - 3ms/step - loss: 0.1036 - val_loss: 0.1063
Epoch 24/80
50/50 - 0s - 3ms/step - loss: 0.1009 - val_loss: 0.1036
Epoch 25/80
50/50 - 0s - 3ms/step - loss: 0.0983 - val_loss: 0.1011
Epoch 26/80
50/50 - 0s - 3ms/step - loss: 0.0966 - val_loss: 0.1033
Epoch 27/80
50/50 - 0s - 3ms/step - loss: 0.0939 - val_loss: 0.0984
Epoch 28/80
50/50 - 0s - 3ms/step - loss: 0.0917 - val_loss: 0.0971
Epoch 29/80
50/50 - 0s - 3ms/step - loss: 0.0892 - val_loss: 0.0986
Epoch 30/80
50/50 - 0s - 3ms/step - loss: 0.0876 - val_loss: 0.0934
Epoch 31/80
50/50 - 0s - 3ms/step - loss: 0.0854 - val_loss: 0.0917
Epoch 32/80
50/50 - 0s - 3ms/step - loss: 0.0835 - val_loss: 0.0909
Epoch 33/80
50/50 - 0s - 3ms/step - loss: 0.0822 - val_loss: 0.0885
Epoch 34/80
50/50 - 0s - 3ms/step - loss: 0.0798 - val_loss: 0.0875
Epoch 35/80
50/50 - 0s - 3ms/step - loss: 0.0788 - val_loss: 0.0849
Epoch 36/80
50/50 - 0s - 3ms/step - loss: 0.0770 - val_loss: 0.0833
Epoch 37/80
50/50 - 0s - 4ms/step - loss: 0.0758 - val_loss: 0.0821
Epoch 38/80
50/50 - 0s - 3ms/step - loss: 0.0742 - val_loss: 0.0802
Epoch 39/80
50/50 - 0s - 3ms/step - loss: 0.0729 - val_loss: 0.0795
Epoch 40/80
50/50 - 0s - 3ms/step - loss: 0.0721 - val_loss: 0.0780
Epoch 41/80
50/50 - 0s - 3ms/step - loss: 0.0707 - val_loss: 0.0768
Epoch 42/80
50/50 - 0s - 3ms/step - loss: 0.0703 - val_loss: 0.0744
Epoch 43/80
50/50 - 0s - 3ms/step - loss: 0.0690 - val_loss: 0.0752
Epoch 44/80
50/50 - 0s - 3ms/step - loss: 0.0687 - val_loss: 0.0732
Epoch 45/80
50/50 - 0s - 3ms/step - loss: 0.0669 - val_loss: 0.0722
Epoch 46/80
50/50 - 0s - 3ms/step - loss: 0.0663 - val_loss: 0.0707
Epoch 47/80
50/50 - 0s - 2ms/step - loss: 0.0658 - val_loss: 0.0703
Epoch 48/80
50/50 - 0s - 2ms/step - loss: 0.0652 - val_loss: 0.0688
Epoch 49/80
50/50 - 0s - 3ms/step - loss: 0.0641 - val_loss: 0.0680
Epoch 50/80
50/50 - 0s - 2ms/step - loss: 0.0639 - val_loss: 0.0699
Epoch 51/80
50/50 - 0s - 3ms/step - loss: 0.0634 - val_loss: 0.0703
Epoch 52/80
50/50 - 0s - 3ms/step - loss: 0.0627 - val_loss: 0.0670
Epoch 53/80
50/50 - 0s - 3ms/step - loss: 0.0619 - val_loss: 0.0658
Epoch 54/80
50/50 - 0s - 3ms/step - loss: 0.0617 - val_loss: 0.0663
Epoch 55/80
50/50 - 0s - 3ms/step - loss: 0.0612 - val_loss: 0.0651
Epoch 56/80
50/50 - 0s - 2ms/step - loss: 0.0606 - val_loss: 0.0673
Epoch 57/80
50/50 - 0s - 2ms/step - loss: 0.0605 - val_loss: 0.0649
Epoch 58/80
50/50 - 0s - 2ms/step - loss: 0.0600 - val_loss: 0.0641
Epoch 59/80
50/50 - 0s - 2ms/step - loss: 0.0595 - val_loss: 0.0635
Epoch 60/80
50/50 - 0s - 2ms/step - loss: 0.0591 - val_loss: 0.0620
Epoch 61/80
50/50 - 0s - 2ms/step - loss: 0.0586 - val_loss: 0.0639
Epoch 62/80
50/50 - 0s - 2ms/step - loss: 0.0583 - val_loss: 0.0619
Epoch 63/80
50/50 - 0s - 2ms/step - loss: 0.0582 - val_loss: 0.0609
Epoch 64/80
50/50 - 0s - 2ms/step - loss: 0.0575 - val_loss: 0.0619
Epoch 65/80
50/50 - 0s - 2ms/step - loss: 0.0571 - val_loss: 0.0607
Epoch 66/80
50/50 - 0s - 2ms/step - loss: 0.0571 - val_loss: 0.0608
Epoch 67/80
50/50 - 0s - 2ms/step - loss: 0.0570 - val_loss: 0.0605
Epoch 68/80
50/50 - 0s - 2ms/step - loss: 0.0563 - val_loss: 0.0587
Epoch 69/80
50/50 - 0s - 2ms/step - loss: 0.0568 - val_loss: 0.0599
Epoch 70/80
50/50 - 0s - 2ms/step - loss: 0.0558 - val_loss: 0.0584
Epoch 71/80
50/50 - 0s - 2ms/step - loss: 0.0552 - val_loss: 0.0584
Epoch 72/80
50/50 - 0s - 2ms/step - loss: 0.0553 - val_loss: 0.0578
Epoch 73/80
50/50 - 0s - 2ms/step - loss: 0.0548 - val_loss: 0.0574
Epoch 74/80
50/50 - 0s - 2ms/step - loss: 0.0547 - val_loss: 0.0583
Epoch 75/80
50/50 - 0s - 2ms/step - loss: 0.0544 - val_loss: 0.0571
Epoch 76/80
50/50 - 0s - 3ms/step - loss: 0.0544 - val_loss: 0.0575
Epoch 77/80
50/50 - 0s - 2ms/step - loss: 0.0542 - val_loss: 0.0565
Epoch 78/80
50/50 - 0s - 2ms/step - loss: 0.0534 - val_loss: 0.0564
Epoch 79/80
50/50 - 0s - 2ms/step - loss: 0.0533 - val_loss: 0.0565
Epoch 80/80
50/50 - 0s - 2ms/step - loss: 0.0536 - val_loss: 0.0574

In [18]:
#Classifier Using Encoded Features
X_train_enc = encoder.predict(X_train)
X_test_enc = encoder.predict(X_test)

clf = models.Sequential([
    layers.Dense(32, activation='relu', input_shape=(encoding_dim,)),
    layers.Dense(num_classes, activation='softmax')
])

clf.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

clf.fit(
    X_train_enc, y_train,
    validation_split=0.1,
    epochs=80,
    batch_size=32,
    verbose=2
)

acc_auto = evaluate(clf, X_test_enc, y_test)

55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Epoch 1/80

c:\Users\ashee\Desktop\crop project\venv\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

50/50 - 1s - 14ms/step - accuracy: 0.0878 - loss: 3.0264 - val_accuracy: 0.2045 - val_loss: 2.7623
Epoch 2/80
50/50 - 0s - 3ms/step - accuracy: 0.2626 - loss: 2.6291 - val_accuracy: 0.3239 - val_loss: 2.4127
Epoch 3/80
50/50 - 0s - 4ms/step - accuracy: 0.3163 - loss: 2.3437 - val_accuracy: 0.3920 - val_loss: 2.1325
Epoch 4/80
50/50 - 0s - 4ms/step - accuracy: 0.3769 - loss: 2.0987 - val_accuracy: 0.4886 - val_loss: 1.9098
Epoch 5/80
50/50 - 0s - 3ms/step - accuracy: 0.4583 - loss: 1.8993 - val_accuracy: 0.5114 - val_loss: 1.7313
Epoch 6/80
50/50 - 0s - 3ms/step - accuracy: 0.5158 - loss: 1.7213 - val_accuracy: 0.5852 - val_loss: 1.5776
Epoch 7/80
50/50 - 0s - 3ms/step - accuracy: 0.5966 - loss: 1.5739 - val_accuracy: 0.6136 - val_loss: 1.4353
Epoch 8/80
50/50 - 0s - 3ms/step - accuracy: 0.6042 - loss: 1.4465 - val_accuracy: 0.6250 - val_loss: 1.3275
Epoch 9/80
50/50 - 0s - 3ms/step - accuracy: 0.6755 - loss: 1.3355 - val_accuracy: 0.6534 - val_loss: 1.2248
Epoch 10/80
50/50 - 0s - 3ms/step - accuracy: 0.6742 - loss: 1.2421 - val_accuracy: 0.6875 - val_loss: 1.1435
Epoch 11/80
50/50 - 0s - 3ms/step - accuracy: 0.7039 - loss: 1.1605 - val_accuracy: 0.7330 - val_loss: 1.0464
Epoch 12/80
50/50 - 0s - 3ms/step - accuracy: 0.7330 - loss: 1.0858 - val_accuracy: 0.7386 - val_loss: 0.9957
Epoch 13/80
50/50 - 0s - 3ms/step - accuracy: 0.7576 - loss: 1.0227 - val_accuracy: 0.7614 - val_loss: 0.9342
Epoch 14/80
50/50 - 0s - 3ms/step - accuracy: 0.7778 - loss: 0.9651 - val_accuracy: 0.8352 - val_loss: 0.8697
Epoch 15/80
50/50 - 0s - 3ms/step - accuracy: 0.7771 - loss: 0.9161 - val_accuracy: 0.8068 - val_loss: 0.8346
Epoch 16/80
50/50 - 0s - 3ms/step - accuracy: 0.8062 - loss: 0.8715 - val_accuracy: 0.8182 - val_loss: 0.8110
Epoch 17/80
50/50 - 0s - 3ms/step - accuracy: 0.8043 - loss: 0.8342 - val_accuracy: 0.8182 - val_loss: 0.7696
Epoch 18/80
50/50 - 0s - 3ms/step - accuracy: 0.8226 - loss: 0.7986 - val_accuracy: 0.8182 - val_loss: 0.7337
Epoch 19/80
50/50 - 0s - 3ms/step - accuracy: 0.8106 - loss: 0.7676 - val_accuracy: 0.8352 - val_loss: 0.6970
Epoch 20/80
50/50 - 0s - 3ms/step - accuracy: 0.8251 - loss: 0.7397 - val_accuracy: 0.8352 - val_loss: 0.6770
Epoch 21/80
50/50 - 0s - 3ms/step - accuracy: 0.8321 - loss: 0.7115 - val_accuracy: 0.8239 - val_loss: 0.6710
Epoch 22/80
50/50 - 0s - 3ms/step - accuracy: 0.8283 - loss: 0.6909 - val_accuracy: 0.8523 - val_loss: 0.6255
Epoch 23/80
50/50 - 0s - 3ms/step - accuracy: 0.8378 - loss: 0.6713 - val_accuracy: 0.8409 - val_loss: 0.6136
Epoch 24/80
50/50 - 0s - 3ms/step - accuracy: 0.8333 - loss: 0.6494 - val_accuracy: 0.8523 - val_loss: 0.5968
Epoch 25/80
50/50 - 0s - 3ms/step - accuracy: 0.8428 - loss: 0.6315 - val_accuracy: 0.8409 - val_loss: 0.5946
Epoch 26/80
50/50 - 0s - 3ms/step - accuracy: 0.8466 - loss: 0.6152 - val_accuracy: 0.8295 - val_loss: 0.5794
Epoch 27/80
50/50 - 0s - 3ms/step - accuracy: 0.8460 - loss: 0.5977 - val_accuracy: 0.8466 - val_loss: 0.5495
Epoch 28/80
50/50 - 0s - 3ms/step - accuracy: 0.8504 - loss: 0.5853 - val_accuracy: 0.8523 - val_loss: 0.5530
Epoch 29/80
50/50 - 0s - 3ms/step - accuracy: 0.8535 - loss: 0.5723 - val_accuracy: 0.8693 - val_loss: 0.5272
Epoch 30/80
50/50 - 0s - 3ms/step - accuracy: 0.8497 - loss: 0.5574 - val_accuracy: 0.8636 - val_loss: 0.5113
Epoch 31/80
50/50 - 0s - 3ms/step - accuracy: 0.8516 - loss: 0.5474 - val_accuracy: 0.8466 - val_loss: 0.5004
Epoch 32/80
50/50 - 0s - 3ms/step - accuracy: 0.8598 - loss: 0.5333 - val_accuracy: 0.8807 - val_loss: 0.4935
Epoch 33/80
50/50 - 0s - 3ms/step - accuracy: 0.8561 - loss: 0.5257 - val_accuracy: 0.8523 - val_loss: 0.4900
Epoch 34/80
50/50 - 0s - 2ms/step - accuracy: 0.8598 - loss: 0.5162 - val_accuracy: 0.8636 - val_loss: 0.4740
Epoch 35/80
50/50 - 0s - 3ms/step - accuracy: 0.8630 - loss: 0.5053 - val_accuracy: 0.8580 - val_loss: 0.4763
Epoch 36/80
50/50 - 0s - 3ms/step - accuracy: 0.8649 - loss: 0.4968 - val_accuracy: 0.8580 - val_loss: 0.4600
Epoch 37/80
50/50 - 0s - 3ms/step - accuracy: 0.8649 - loss: 0.4865 - val_accuracy: 0.8636 - val_loss: 0.4562
Epoch 38/80
50/50 - 0s - 2ms/step - accuracy: 0.8668 - loss: 0.4806 - val_accuracy: 0.8693 - val_loss: 0.4472
Epoch 39/80
50/50 - 0s - 3ms/step - accuracy: 0.8643 - loss: 0.4709 - val_accuracy: 0.8466 - val_loss: 0.4417
Epoch 40/80
50/50 - 0s - 3ms/step - accuracy: 0.8693 - loss: 0.4603 - val_accuracy: 0.8750 - val_loss: 0.4281
Epoch 41/80
50/50 - 0s - 3ms/step - accuracy: 0.8737 - loss: 0.4577 - val_accuracy: 0.8750 - val_loss: 0.4245
Epoch 42/80
50/50 - 0s - 3ms/step - accuracy: 0.8699 - loss: 0.4485 - val_accuracy: 0.8523 - val_loss: 0.4196
Epoch 43/80
50/50 - 0s - 4ms/step - accuracy: 0.8699 - loss: 0.4418 - val_accuracy: 0.8523 - val_loss: 0.4145
Epoch 44/80
50/50 - 0s - 3ms/step - accuracy: 0.8681 - loss: 0.4367 - val_accuracy: 0.8636 - val_loss: 0.4060
Epoch 45/80
50/50 - 0s - 3ms/step - accuracy: 0.8712 - loss: 0.4318 - val_accuracy: 0.8636 - val_loss: 0.4078
Epoch 46/80
50/50 - 0s - 3ms/step - accuracy: 0.8775 - loss: 0.4246 - val_accuracy: 0.8523 - val_loss: 0.4056
Epoch 47/80
50/50 - 0s - 3ms/step - accuracy: 0.8737 - loss: 0.4183 - val_accuracy: 0.8636 - val_loss: 0.3931
Epoch 48/80
50/50 - 0s - 3ms/step - accuracy: 0.8763 - loss: 0.4121 - val_accuracy: 0.8580 - val_loss: 0.3898
Epoch 49/80
50/50 - 0s - 3ms/step - accuracy: 0.8744 - loss: 0.4054 - val_accuracy: 0.8693 - val_loss: 0.3913
Epoch 50/80
50/50 - 0s - 3ms/step - accuracy: 0.8826 - loss: 0.4018 - val_accuracy: 0.8523 - val_loss: 0.3840
Epoch 51/80
50/50 - 0s - 3ms/step - accuracy: 0.8794 - loss: 0.3956 - val_accuracy: 0.8750 - val_loss: 0.3766
Epoch 52/80
50/50 - 0s - 3ms/step - accuracy: 0.8870 - loss: 0.3913 - val_accuracy: 0.8409 - val_loss: 0.3748
Epoch 53/80
50/50 - 0s - 3ms/step - accuracy: 0.8775 - loss: 0.3885 - val_accuracy: 0.8636 - val_loss: 0.3720
Epoch 54/80
50/50 - 0s - 3ms/step - accuracy: 0.8819 - loss: 0.3835 - val_accuracy: 0.8693 - val_loss: 0.3738
Epoch 55/80
50/50 - 0s - 3ms/step - accuracy: 0.8838 - loss: 0.3788 - val_accuracy: 0.8523 - val_loss: 0.3794
Epoch 56/80
50/50 - 0s - 3ms/step - accuracy: 0.8813 - loss: 0.3793 - val_accuracy: 0.8693 - val_loss: 0.3714
Epoch 57/80
50/50 - 0s - 3ms/step - accuracy: 0.8819 - loss: 0.3719 - val_accuracy: 0.8523 - val_loss: 0.3587
Epoch 58/80
50/50 - 0s - 3ms/step - accuracy: 0.8864 - loss: 0.3663 - val_accuracy: 0.8636 - val_loss: 0.3595
Epoch 59/80
50/50 - 0s - 3ms/step - accuracy: 0.8902 - loss: 0.3616 - val_accuracy: 0.8523 - val_loss: 0.3532
Epoch 60/80
50/50 - 0s - 3ms/step - accuracy: 0.8889 - loss: 0.3568 - val_accuracy: 0.8864 - val_loss: 0.3483
Epoch 61/80
50/50 - 0s - 3ms/step - accuracy: 0.8927 - loss: 0.3552 - val_accuracy: 0.8750 - val_loss: 0.3473
Epoch 62/80
50/50 - 0s - 3ms/step - accuracy: 0.8952 - loss: 0.3517 - val_accuracy: 0.8636 - val_loss: 0.3459
Epoch 63/80
50/50 - 0s - 3ms/step - accuracy: 0.8952 - loss: 0.3472 - val_accuracy: 0.8636 - val_loss: 0.3439
Epoch 64/80
50/50 - 0s - 3ms/step - accuracy: 0.8883 - loss: 0.3455 - val_accuracy: 0.8920 - val_loss: 0.3338
Epoch 65/80
50/50 - 0s - 3ms/step - accuracy: 0.8939 - loss: 0.3405 - val_accuracy: 0.8636 - val_loss: 0.3318
Epoch 66/80
50/50 - 0s - 3ms/step - accuracy: 0.8971 - loss: 0.3387 - val_accuracy: 0.8750 - val_loss: 0.3319
Epoch 67/80
50/50 - 0s - 3ms/step - accuracy: 0.8990 - loss: 0.3352 - val_accuracy: 0.8693 - val_loss: 0.3324
Epoch 68/80
50/50 - 0s - 3ms/step - accuracy: 0.8996 - loss: 0.3301 - val_accuracy: 0.8977 - val_loss: 0.3271
Epoch 69/80
50/50 - 0s - 3ms/step - accuracy: 0.9015 - loss: 0.3293 - val_accuracy: 0.8693 - val_loss: 0.3236
Epoch 70/80
50/50 - 0s - 3ms/step - accuracy: 0.8990 - loss: 0.3263 - val_accuracy: 0.8636 - val_loss: 0.3213
Epoch 71/80
50/50 - 0s - 4ms/step - accuracy: 0.8958 - loss: 0.3225 - val_accuracy: 0.8977 - val_loss: 0.3190
Epoch 72/80
50/50 - 0s - 3ms/step - accuracy: 0.9034 - loss: 0.3200 - val_accuracy: 0.8750 - val_loss: 0.3211
Epoch 73/80
50/50 - 0s - 3ms/step - accuracy: 0.9040 - loss: 0.3179 - val_accuracy: 0.8693 - val_loss: 0.3128
Epoch 74/80
50/50 - 0s - 3ms/step - accuracy: 0.9009 - loss: 0.3143 - val_accuracy: 0.8750 - val_loss: 0.3182
Epoch 75/80
50/50 - 0s - 3ms/step - accuracy: 0.9072 - loss: 0.3115 - val_accuracy: 0.8750 - val_loss: 0.3223
Epoch 76/80
50/50 - 0s - 3ms/step - accuracy: 0.9034 - loss: 0.3111 - val_accuracy: 0.8864 - val_loss: 0.3056
Epoch 77/80
50/50 - 0s - 3ms/step - accuracy: 0.9034 - loss: 0.3056 - val_accuracy: 0.8693 - val_loss: 0.3119
Epoch 78/80
50/50 - 0s - 3ms/step - accuracy: 0.9053 - loss: 0.3082 - val_accuracy: 0.8693 - val_loss: 0.3153
Epoch 79/80
50/50 - 0s - 3ms/step - accuracy: 0.9028 - loss: 0.3027 - val_accuracy: 0.8750 - val_loss: 0.3139
Epoch 80/80
50/50 - 0s - 2ms/step - accuracy: 0.9078 - loss: 0.3011 - val_accuracy: 0.8693 - val_loss: 0.3024
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Accuracy: 0.9181818181818182
              precision    recall  f1-score   support

       apple       0.95      1.00      0.98        20
      banana       1.00      1.00      1.00        20
   blackgram       0.80      1.00      0.89        20
    chickpea       1.00      1.00      1.00        20
     coconut       1.00      1.00      1.00        20
      coffee       1.00      0.95      0.97        20
      cotton       0.95      1.00      0.98        20
      grapes       0.95      0.95      0.95        20
        jute       0.75      0.90      0.82        20
 kidneybeans       0.95      1.00      0.98        20
      lentil       0.95      0.90      0.92        20
       maize       1.00      0.95      0.97        20
       mango       0.83      1.00      0.91        20
   mothbeans       0.94      0.75      0.83        20
    mungbean       1.00      1.00      1.00        20
   muskmelon       0.95      1.00      0.98        20
      orange       0.70      0.70      0.70        20
      papaya       0.81      0.65      0.72        20
  pigeonpeas       1.00      0.80      0.89        20
 pomegranate       0.80      0.80      0.80        20
        rice       0.94      0.85      0.89        20
  watermelon       1.00      1.00      1.00        20

    accuracy                           0.92       440
   macro avg       0.92      0.92      0.92       440
weighted avg       0.92      0.92      0.92       440

In [20]:
#COMPARE ALL ALGORITHMS
# Compare all algorithms
results = {
    "DNN / MLP": acc_mlp,
    "TabNet": acc_tabnet,
    "Autoencoder + DNN": acc_auto,
    "Keras Transformer": acc_trans
}

import pandas as pd
pd.DataFrame(results, index=["Accuracy"]).T.sort_values(by="Accuracy", ascending=False)

                   Accuracy
DNN / MLP          0.984091
Autoencoder + DNN  0.918182
Keras Transformer  0.688636
TabNet             0.102273

In [21]:
#TEST NEW VALUE ON DNN / MLP
sample = {
    'N': 50,
    'P': 40,
    'K': 40,
    'temperature': 25,
    'humidity': 70,
    'ph': 6.5,
    'rainfall': 150
}

import pandas as pd
import numpy as np

df_sample = pd.DataFrame([sample])
scaled = scaler.transform(df_sample)

pred_prob = mlp.predict(scaled)
pred_class = np.argmax(pred_prob)
print("Predicted Crop:", le.inverse_transform([pred_class])[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
Predicted Crop: jute

In [22]:
#TEST NEW VALUE ON TABNet
sample = [
    sample['N'], sample['P'], sample['K'], 
    sample['temperature'], sample['humidity'], 
    sample['ph'], sample['rainfall']
]

import numpy as np
tab_pred = tabnet.predict(np.array([sample]))
print("Predicted Crop (TabNet):", le.inverse_transform(tab_pred)[0])

Predicted Crop (TabNet): orange

In [23]:
#TEST NEW VALUE ON Autoencoder+DNN
df_sample = pd.DataFrame([sample])
scaled = scaler.transform(df_sample)

# Encode
encoded = encoder.predict(scaled)

# Classify
pred_prob = clf.predict(encoded)
pred_class = np.argmax(pred_prob)
print("Predicted Crop (Autoencoder+DNN):", le.inverse_transform([pred_class])[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
Predicted Crop (Autoencoder+DNN): jute

c:\Users\ashee\Desktop\crop project\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [24]:
#TEST NEW VALUE ON Keras Transformer
df_sample = pd.DataFrame([sample])
scaled = scaler.transform(df_sample)

# reshape for transformer (batch, seq_len, channels)
trans_input = scaled.reshape(1, len(sample), 1)

pred_prob = transformer_model.predict(trans_input)
pred_class = np.argmax(pred_prob)
print("Predicted Crop (Transformer):", le.inverse_transform([pred_class])[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
Predicted Crop (Transformer): maize

c:\Users\ashee\Desktop\crop project\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [25]:
#Testing Function
def test_value(model, sample_dict, model_type):
    df_sample = pd.DataFrame([sample_dict])

    if model_type == "tabnet":
        arr = df_sample.values
        pred = model.predict(arr)
        return le.inverse_transform(pred)[0]

    if model_type == "transformer":
        scaled = scaler.transform(df_sample)
        reshaped = scaled.reshape(1, len(sample_dict), 1)
        pred = model.predict(reshaped)
        return le.inverse_transform([np.argmax(pred)])[0]

    if model_type == "autoencoder":
        scaled = scaler.transform(df_sample)
        encoded = encoder.predict(scaled)
        pred = clf.predict(encoded)
        return le.inverse_transform([np.argmax(pred)])[0]

    # default for MLP/DNN
    scaled = scaler.transform(df_sample)
    pred = model.predict(scaled)
    return le.inverse_transform([np.argmax(pred)])[0]